export type Lane = 'top' | 'jungle' | 'mid' | 'bot' | 'support';

export const LANE_LABELS: Record<Lane, string> = {
  top: 'Top',
  jungle: 'Jungle',
  mid: 'Mid',
  bot: 'Bot',
  support: 'Support',
};

// Maps champion ID -> array of lanes they commonly play
// Most champions have 1-2 common lanes
export const CHAMPION_LANES: Record<string, Lane[]> = {
  Aatrox: ['top'],
  Ahri: ['mid'],
  Akali: ['mid', 'top'],
  Akshan: ['mid', 'top'],
  Alistar: ['support'],
  Ambessa: ['top'],
  Amumu: ['jungle', 'support'],
  Anivia: ['mid'],
  Annie: ['mid', 'support'],
  Aphelios: ['bot'],
  Ashe: ['bot', 'support'],
  AurelionSol: ['mid'],
  Aurora: ['mid', 'top'],
  Azir: ['mid'],
  Bard: ['support'],
  Belveth: ['jungle'],
  Blitzcrank: ['support'],
  Brand: ['support', 'mid'],
  Braum: ['support'],
  Briar: ['jungle'],
  Caitlyn: ['bot'],
  Camille: ['top'],
  Cassiopeia: ['mid'],
  Chogath: ['top', 'mid'],
  Corki: ['mid'],
  Darius: ['top'],
  Diana: ['jungle', 'mid'],
  DrMundo: ['top', 'jungle'],
  Draven: ['bot'],
  Ekko: ['jungle', 'mid'],
  Elise: ['jungle'],
  Evelynn: ['jungle'],
  Ezreal: ['bot'],
  Fiddlesticks: ['jungle'],
  Fiora: ['top'],
  Fizz: ['mid'],
  Galio: ['mid', 'support'],
  Gangplank: ['top', 'mid'],
  Garen: ['top'],
  Gnar: ['top'],
  Gragas: ['jungle', 'top'],
  Graves: ['jungle'],
  Gwen: ['top'],
  Hecarim: ['jungle'],
  Heimerdinger: ['mid', 'top'],
  Hwei: ['mid', 'support'],
  Illaoi: ['top'],
  Irelia: ['top', 'mid'],
  Ivern: ['jungle'],
  Janna: ['support'],
  JarvanIV: ['jungle'],
  Jax: ['top', 'jungle'],
  Jayce: ['top', 'mid'],
  Jhin: ['bot'],
  Jinx: ['bot'],
  KSante: ['top'],
  Kaisa: ['bot'],
  Kalista: ['bot'],
  Karma: ['support', 'mid'],
  Karthus: ['jungle', 'mid'],
  Kassadin: ['mid'],
  Katarina: ['mid'],
  Kayle: ['top'],
  Kayn: ['jungle'],
  Kennen: ['top'],
  Khazix: ['jungle'],
  Kindred: ['jungle'],
  Kled: ['top'],
  KogMaw: ['bot'],
  Leblanc: ['mid'],
  LeeSin: ['jungle'],
  Leona: ['support'],
  Lillia: ['jungle'],
  Lissandra: ['mid'],
  Lucian: ['bot', 'mid'],
  Lulu: ['support'],
  Lux: ['support', 'mid'],
  Malphite: ['top', 'support'],
  Malzahar: ['mid'],
  Maokai: ['support', 'jungle'],
  MasterYi: ['jungle'],
  Mel: ['mid'],
  Milio: ['support'],
  MissFortune: ['bot'],
  MonkeyKing: ['top', 'jungle'],
  Mordekaiser: ['top'],
  Morgana: ['support', 'mid'],
  Naafiri: ['mid', 'jungle'],
  Nami: ['support'],
  Nasus: ['top'],
  Nautilus: ['support'],
  Neeko: ['mid', 'support'],
  Nidalee: ['jungle'],
  Nilah: ['bot'],
  Nocturne: ['jungle'],
  Nunu: ['jungle'],
  Olaf: ['top', 'jungle'],
  Orianna: ['mid'],
  Ornn: ['top'],
  Pantheon: ['support', 'mid', 'top'],
  Poppy: ['top', 'jungle', 'support'],
  Pyke: ['support'],
  Qiyana: ['mid', 'jungle'],
  Quinn: ['top'],
  Rakan: ['support'],
  Rammus: ['jungle'],
  RekSai: ['jungle'],
  Rell: ['support'],
  Renata: ['support'],
  Renekton: ['top'],
  Rengar: ['jungle', 'top'],
  Riven: ['top'],
  Rumble: ['top', 'mid'],
  Ryze: ['mid', 'top'],
  Samira: ['bot'],
  Sejuani: ['jungle', 'top'],
  Senna: ['support', 'bot'],
  Seraphine: ['support', 'mid'],
  Sett: ['top', 'support'],
  Shaco: ['jungle'],
  Shen: ['top'],
  Shyvana: ['jungle'],
  Singed: ['top'],
  Sion: ['top'],
  Sivir: ['bot'],
  Skarner: ['jungle'],
  Smolder: ['bot', 'mid'],
  Sona: ['support'],
  Soraka: ['support'],
  Swain: ['support', 'mid'],
  Sylas: ['mid'],
  Syndra: ['mid'],
  TahmKench: ['top', 'support'],
  Taliyah: ['mid', 'jungle'],
  Talon: ['mid', 'jungle'],
  Taric: ['support'],
  Teemo: ['top'],
  Thresh: ['support'],
  Tristana: ['bot', 'mid'],
  Trundle: ['jungle', 'top'],
  Tryndamere: ['top'],
  TwistedFate: ['mid'],
  Twitch: ['bot'],
  Udyr: ['jungle', 'top'],
  Urgot: ['top'],
  Varus: ['bot', 'mid'],
  Vayne: ['bot', 'top'],
  Veigar: ['mid'],
  Velkoz: ['mid', 'support'],
  Vex: ['mid'],
  Vi: ['jungle'],
  Viego: ['jungle'],
  Viktor: ['mid'],
  Vladimir: ['mid', 'top'],
  Volibear: ['top', 'jungle'],
  Warwick: ['jungle', 'top'],
  Xayah: ['bot'],
  Xerath: ['mid', 'support'],
  XinZhao: ['jungle'],
  Yasuo: ['mid', 'bot'],
  Yone: ['mid', 'top'],
  Yorick: ['top'],
  Yunara: ['mid', 'support'],
  Yuumi: ['support'],
  Zaahen: ['top', 'jungle'],
  Zac: ['jungle'],
  Zed: ['mid'],
  Zeri: ['bot'],
  Ziggs: ['bot', 'mid'],
  Zilean: ['support', 'mid'],
  Zoe: ['mid'],
  Zyra: ['support'],
};

// Pick order maps to lane positions for each team
// In pro play, pick order often follows: flexible early, carries later
export const PICK_LANE_ORDER: Lane[] = ['top', 'jungle', 'mid', 'bot', 'support'];
